# Generated by Django 2.1.1 on 2018-09-24 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Host Name', max_length=50)),
                ('cpu', models.CharField(blank=True, help_text='CPU', max_length=4)),
                ('ram', models.CharField(blank=True, help_text='RAM', max_length=4)),
                ('conf_location', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Description')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Tool Name', max_length=20)),
                ('log_location', models.CharField(blank=True, max_length=20)),
                ('log_info', models.CharField(blank=True, max_length=200, verbose_name='Log')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Description')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEOD_Mon.Host')),
            ],
        ),
    ]
