# Generated by Django 2.1.1 on 2018-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEOD_Mon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(blank=True, editable=False, help_text='CPU', max_length=4),
        ),
        migrations.AlterField(
            model_name='host',
            name='ram',
            field=models.CharField(blank=True, editable=False, help_text='RAM', max_length=4),
        ),
        migrations.AlterField(
            model_name='tool',
            name='log_info',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Log'),
        ),
    ]
